### ISSUE TITLE
site offline

### ISSUE THREAD

**Issue by tkovs** [ohnorobo/pokemon#11]
The [site](http://www.frankenpokemon.me/) is down.

**Comment by ohnorobo** [comment]
Thanks for letting us know. I'll take a look into it.

**Comment by ohnorobo** [comment]
The original hosting has gone away. I'll see if it's easy to bring back up on heroku where I have some other stuff. If not then mors ultima linea rerum est.

**Comment by tkovs** [comment]
Okay.

**Comment by ohnorobo** [comment]
The site's back up now at https://frankenpokemon.herokuapp.com
