### ISSUE TITLE
HackBeanpot is one word.

### ISSUE THREAD

**Issue by aceyoung9** [ohnorobo/pokemon#2]
no space. :stuck_out_tongue:

**Comment by ohnorobo** [comment]
check

**Comment by aceyoung9** [comment]
What do you mean, check. Do you want me to show you some incorporation papers for a petty online fight over your banner image?

**Comment by ali** [comment]
@aliceyoung9 It's actually two words, camel cased. Get it right.

**Comment by ali** [comment]
@aliceyoung9 Do you even captain?

**Comment by wolfd** [comment]
:cactus:

**Comment by aceyoung9** [comment]
Don't listen to @ali . Despite popular belief, he's not a lead organizer. Even if people keep asking him for extra tickets.

**Comment by ali** [comment]
@aliceyoung9 I deserve a shiny for putting up with you.
