### ISSUE TITLE
Name, text and type regenerated every reload for a given pokemon

### ISSUE THREAD

**Issue by ryansturmer** [ohnorobo/pokemon#9]
For a given pokemon URL, the title/text/type of the pokemon is regenerated each refresh, while the pokemon body image stays the same.  This makes it impossible to use the URL to share pokemans, since the title/type/description are not deterministic.

![x270909744_cd078aad8f jpg pagespeed ic 6avpudizn3](https://cloud.githubusercontent.com/assets/1383181/6199983/4437f4f6-b430-11e4-925e-4e7809a42390.jpg)

FWIW, I disagree with issue #7, I think the markov chain generated sentences are pretty wacky and fun.  Zany, even.

**Comment by ohnorobo** [comment]
This is excellent :+1:

**Comment by ryansturmer** [comment]
How were the names generated, btw?  Markov model also?

**Comment by ohnorobo** [comment]
er... [something like that](http://fantasynamegenerators.com/pokemon-names.php)
